import type { Metadata } from "next";
import { Inter, Montserrat, Poppins } from "next/font/google";
import "../styles/globals.css";
import Navigation from "../components/ui/Navigation";
import Footer from "../components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-white`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
